spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
app:
  photos:
    photo-path: /Users/jdholding/srv/houseplants/
    original-path: /Users/jdholding/srv/houseplants/originals/
    thumbnail-path: /Users/jdholding/srv/houseplants/thumbnails/
  url:
    context: http://localhost:8080  