spring:
  application:
    name: houseplants
  datasource:
    url: jdbc:postgresql://localhost:5445/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
    servlet:
      context-path: /
