spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
app:
  photos:
    original-path: Users/jdholding/srv/houseplants/originals
    thumbnail-path: Users/jdholding/srv/houseplants/thumbnails